<a href="https://colab.research.google.com/github/PatrickRuan/2nd-ML100Days/blob/master/Day_040_HW%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [0]:
import numpy as np
from sklearn.model_selection import KFold, train_test_split
from sklearn.linear_model import LogisticRegression, Lasso, Ridge, LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn import datasets

In [0]:
boston = datasets.load_boston()
print(boston.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [0]:

X_train, X_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=43)

In [0]:
reg = LinearRegression()
reg.fit(X_train, y_train)
pred = reg.predict(X_test)
print(f'coef. of reg is {reg.coef_}')
print(f'mse of reg is, {mean_squared_error(y_test, pred)}')

coef. of reg is [-8.38540942e-02  4.92121667e-02  8.54515795e-03  2.74805637e+00
 -1.91880432e+01  3.39570396e+00  1.02258557e-02 -1.45389754e+00
  2.97780830e-01 -1.13032017e-02 -9.75477983e-01  7.99097249e-03
 -5.84517837e-01]
mse of reg is, 22.01861344950045


In [0]:
regL1 = Lasso()
regL1.fit(X_train, y_train)
pred = regL1.predict(X_test)
print(f'coef. of regL1 is {regL1.coef_}')
print(f'mse of regL1 is, {mean_squared_error(y_test, pred)}')

coef. of regL1 is [-0.04088362  0.05751707 -0.          0.         -0.          0.59285995
  0.03319793 -0.57067996  0.27870338 -0.01594815 -0.76358845  0.00831679
 -0.81382874]
mse of regL1 is, 29.831894847003777


In [0]:
regL2 = Ridge()
regL2.fit(X_train, y_train)
pred = regL2.predict(X_test)
print(f'coef. of regL2 is {regL2.coef_}')
print(f'mse of regL2 is, {mean_squared_error(y_test, pred)}')

coef. of regL2 is [-7.82562830e-02  5.11551292e-02 -2.96111555e-02  2.63921803e+00
 -1.05522726e+01  3.43583813e+00  2.30269132e-03 -1.33561735e+00
  2.80047124e-01 -1.20432815e-02 -8.88244871e-01  8.77509022e-03
 -5.89841081e-01]
mse of regL2 is, 21.890670950212623
